name: ${project.artifactId}
version: ${project.version}
description: Adds back old /kill suicide mechanic for players without the cynathans.command.kill permission.
authors: [ Cynathan ]
api-version: 1.16
main: not.hub.cynathanskill.Plugin
